version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      mantine:
        patterns:
          - "@mantine/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"

  - package-ecosystem: "pip"
    directory: "/semgrep-service"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
