/**
 * Tests for AI Attribution Detection
 */

import {
  assertEquals,
  assertExists,
} from 'https://deno.land/std@0.208.0/assert/mod.ts';
import {
  describe,
  it,
} from 'https://deno.land/std@0.208.0/testing/bdd.ts';

import {
  checkFileForAiAttribution,
  checkCommitsForAiAttribution,
} from '../ai-attribution.ts';

describe('AI Attribution - File Checks', () => {
  it('should detect co-authored-by claude', () => {
    const patch = `@@ -1,3 +1,5 @@\n+Co-Authored-By: Claude <noreply@anthropic.com>\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
    assertEquals(findings[0].ruleId, 'ai-attribution-file');
    assertEquals(findings[0].severity, 'error');
  });

  it('should detect co-authored-by openai', () => {
    const patch = `@@ -1,3 +1,5 @@\n+Co-authored-by: GPT-4 <noreply@openai.com>\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect co-authored-by copilot', () => {
    const patch = `@@ -1,3 +1,5 @@\n+co-authored-by: GitHub Copilot\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect co-authored-by gemini', () => {
    const patch = `@@ -1,3 +1,5 @@\n+co-authored-by: Gemini <noreply@google.com>\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "made by claude"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Made by Claude\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "generated by ai"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Generated by AI\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "written by ai"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+# Written by AI assistant\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "claude code"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Built with Claude Code\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "claude opus"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Claude Opus generated this\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "gpt-4"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// GPT-4 helped write this\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect "chatgpt"', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// ChatGPT was used here\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect @anthropic.com email', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Author: user@anthropic.com\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should detect @openai.com email', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Contact: noreply@openai.com\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should be case-insensitive', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// MADE BY CLAUDE\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length >= 1, true);
  });

  it('should only check added lines (+ prefix)', () => {
    const patch = `@@ -1,3 +1,5 @@\n-Co-Authored-By: Claude <noreply@anthropic.com>\n const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length, 0);
  });

  it('should skip +++ header lines', () => {
    const patch = `+++ b/Co-Authored-By-Claude.ts\n@@ -1,3 +1,5 @@\n+const x = 1;`;
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length, 0);
  });

  it('should not produce false positives on normal code', () => {
    const patch = `@@ -1,5 +1,7 @@\n+import { useState } from 'react';\n+\n+export function App() {\n+  const [count, setCount] = useState(0);\n+  return <div>{count}</div>;\n+}`;
    const findings = checkFileForAiAttribution('App.tsx', patch);
    assertEquals(findings.length, 0);
  });

  it('should not produce false positives on common words', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// This function creates a new user for the application\n+const claude = new Client('Claude API');`;
    // "claude" as a variable name without the AI patterns should not match
    // But "Claude API" might match "claude" pattern - let's check
    // Actually "claude code", "claude opus", "claude sonnet", "claude haiku" are the patterns
    // Just "Claude API" doesn't match any of them
    const findings = checkFileForAiAttribution('file.ts', patch);
    assertEquals(findings.length, 0);
  });

  it('should return empty for empty patch', () => {
    const findings = checkFileForAiAttribution('file.ts', '');
    assertEquals(findings.length, 0);
  });

  it('should include file and source info', () => {
    const patch = `@@ -1,3 +1,5 @@\n+// Made by AI\n const x = 1;`;
    const findings = checkFileForAiAttribution('src/utils.ts', patch);
    assertEquals(findings[0].file, 'src/utils.ts');
    assertEquals(findings[0].source, 'static-analysis');
    assertEquals(findings[0].category, 'ai-attribution');
  });
});

describe('AI Attribution - Commit Checks', () => {
  it('should detect AI attribution in commit messages', () => {
    const commits = [
      { sha: 'abc1234567890', message: 'feat: add login\n\nCo-Authored-By: Claude <noreply@anthropic.com>' },
    ];
    const findings = checkCommitsForAiAttribution(commits, 1);
    assertEquals(findings.length, 1);
    assertEquals(findings[0].ruleId, 'ai-attribution-commit');
    assertEquals(findings[0].severity, 'error');
  });

  it('should provide amend suggestion for last commit', () => {
    const commits = [
      { sha: 'abc1234567890', message: 'feat: add login\n\nCo-Authored-By: Claude <noreply@anthropic.com>' },
    ];
    const findings = checkCommitsForAiAttribution(commits, 1);
    assertExists(findings[0].suggestion);
    assertEquals(findings[0].suggestion!.includes('--amend'), true);
  });

  it('should provide rebase suggestion for non-last commit', () => {
    const commits = [
      { sha: 'abc1234567890', message: 'feat: login\n\nCo-Authored-By: Claude <noreply@anthropic.com>' },
      { sha: 'def4567890123', message: 'feat: signup' },
    ];
    const findings = checkCommitsForAiAttribution(commits, 2);
    assertEquals(findings.length, 1);
    assertExists(findings[0].suggestion);
    assertEquals(findings[0].suggestion!.includes('rebase'), true);
  });

  it('should detect multiple commits with attribution', () => {
    const commits = [
      { sha: 'abc1234567890', message: 'feat: login\n\nMade by Claude' },
      { sha: 'def4567890123', message: 'fix: bug\n\nGenerated by AI' },
    ];
    const findings = checkCommitsForAiAttribution(commits, 2);
    assertEquals(findings.length, 2);
  });

  it('should not flag clean commits', () => {
    const commits = [
      { sha: 'abc1234567890', message: 'feat(auth): add login endpoint' },
      { sha: 'def4567890123', message: 'fix(api): handle timeout errors' },
    ];
    const findings = checkCommitsForAiAttribution(commits, 2);
    assertEquals(findings.length, 0);
  });

  it('should include short SHA in message', () => {
    const commits = [
      { sha: 'abc1234567890', message: 'Co-Authored-By: Claude <noreply@anthropic.com>' },
    ];
    const findings = checkCommitsForAiAttribution(commits, 1);
    assertEquals(findings[0].message.includes('abc1234'), true);
  });
});
