CREATE TABLE "explanation_invocations" (
	"id" serial PRIMARY KEY NOT NULL,
	"invocation_key" varchar(64) NOT NULL,
	"forge_instance" text NOT NULL,
	"installation_id" text NOT NULL,
	"actor_id" text NOT NULL,
	"repository_id" text NOT NULL,
	"pull_request_number" integer NOT NULL,
	"requested_head_sha" text NOT NULL,
	"source_comment_id" text NOT NULL,
	"question_hash" varchar(64) NOT NULL,
	"question" text NOT NULL,
	"execution_status" varchar(32) DEFAULT 'PENDING' NOT NULL,
	"execution_fence" text,
	"dispatch_reserved_at" timestamp,
	"dispatch_lease_expires_at" timestamp,
	"outcome_status" varchar(32),
	"outcome_answer" text,
	"outcome_completed_at" timestamp,
	"progress_status" varchar(32),
	"progress_version" integer DEFAULT 0 NOT NULL,
	"progress_publication_status" varchar(32) DEFAULT 'NOT_STARTED' NOT NULL,
	"progress_publication_create_started_at" timestamp,
	"progress_comment_id" bigint,
	"progress_expected_bot_author_id" bigint,
	"progress_publication_fence" text,
	"progress_publication_version" integer DEFAULT 0 NOT NULL,
	"answer_publication_status" varchar(32) DEFAULT 'NOT_STARTED' NOT NULL,
	"answer_publication_create_started_at" timestamp,
	"answer_comment_id" bigint,
	"answer_expected_bot_author_id" bigint,
	"answer_publication_fence" text,
	"answer_publication_version" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "uq_explanation_invocations_key" UNIQUE("invocation_key"),
	CONSTRAINT "chk_explanation_invocations_execution_status" CHECK ("explanation_invocations"."execution_status" IN ('PENDING', 'DISPATCH_RESERVED', 'ANSWERED', 'INVALID', 'UNAUTHORIZED', 'DISABLED', 'STALE', 'AI_UNAVAILABLE', 'AMBIGUOUS')),
	CONSTRAINT "chk_explanation_invocations_progress_publication_status" CHECK ("explanation_invocations"."progress_publication_status" IN ('NOT_STARTED', 'CREATE_STARTED', 'PUBLISHED', 'STALE', 'AMBIGUOUS')),
	CONSTRAINT "chk_explanation_invocations_answer_publication_status" CHECK ("explanation_invocations"."answer_publication_status" IN ('NOT_STARTED', 'CREATE_STARTED', 'PUBLISHED', 'STALE', 'AMBIGUOUS'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX "uq_explanation_invocations_full_identity" ON "explanation_invocations" USING btree ("forge_instance","installation_id","actor_id","repository_id","pull_request_number","requested_head_sha","source_comment_id","question_hash");